name: Auto Merge to Stage

on:
  push:
    branches-ignore:
      - "main"
      - "stage"

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "disnel@fonoma.com"
          git config --global user.name "GitHub Action Reloaded"

      - name: Merge to Stage
        run: |
          git fetch origin stage:stage
          git checkout stage
          git merge ${{ github.ref_name }} --no-ff --no-edit
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.ACTIONS }}" push origin stage
